add powershell script
datawire/emojivoto pull request #56
Opened 2023-05-09 21:38 UTC by arturogonzalez58

This PR adds a new script to run in Windows and Powershell. We only support running the intermediate tour in the application using Linux and MacOs. This script is the first iteration to support Windows in the intermediate tour.

In order to test the pr you need the following:
- Windows(only windows 10 tested)
- kubectl
- Ability to use Powershell as an administrator
- Access to `app.getambassador.io`
- it is assuming that you doesn't have telepresence installed

Kown issues
- Telepresence is not updatable from the script
- If the user cancels the telepresence installation, the script is going to continue

Testing:
1. Go to app.getambassador.io and start the tour
<img width="1046" alt="image" src="https://github.com/datawire/emojivoto/assets/42355868/08862df2-e97e-4eb3-9ce3-f719b57570c1">

2. Click on `Don't have a cluster? get a free one!`

4. Follow the instruction in the tour until step 3: Run the script
<img width="715" alt="image" src="https://github.com/datawire/emojivoto/assets/42355868/8ad0b31a-5fb1-4405-91b6-161d8503913c">

5. Using power shell as administrator move the branch of this PR:
```git checkout agv/dev/windows_script```

6. Then set the environment variable with the `AMBASSADOR_API_KEY` provided in the tour
```New-Item -Path Env:\AMBASSADOR_API_KEY -Value NDFSFADS....```

7.  Then run the script
```.\setup_dev_env.sp1```

2023-05-26 21:03 UTC, joseldmc commented on emojivoto-web-app/js/setup_dev_env.ps1
> +        $telepresence_download_url = "https://app.getambassador.io/download/tel2/windows/amd64/latest/telepresence-setup.exe"
Let's target a specific version.

2023-05-29 18:17 UTC, shepz commented on emojivoto-web-app/js/setup_dev_env.ps1
> +param([string]$action="TP_SCIPT")
typo ?
```suggestion
param([string]$action="TP_SCRIPT")
```

2023-05-29 18:17 UTC, shepz commented on emojivoto-web-app/js/setup_dev_env.ps1
> +set_os_arch
shouldn't we test the arch as a first step ?

2023-05-29 18:17 UTC, shepz commented on emojivoto-web-app/js/setup_dev_env.ps1
> +        # New-Item -Path Env:\AMBASSADOR_API_KEY -Value 'NTIyOWExZDktYTc5...'
remove comments ?

2023-05-29 19:01 UTC, joseldmc approved these changes

2023-05-30 13:12 UTC, knlambert requested changes

2023-05-30 13:12 UTC, knlambert commented on emojivoto-web-app/js/setup_dev_env.ps1
> +    telepresence helm upgrade --team-mode 2>&1 | Out-Null
Is telepresence supposed to be already installed ?

2023-05-30 13:12 UTC, knlambert commented on emojivoto-web-app/js/setup_dev_env.ps1
> +    telepresence intercept "$interceptName" --docker --context default -n "$Global:EMOJIVOTO_NS" --service web-app --port 8083:80 --ingress-port 80 --ingress-host "$svcName.ambassador" --ingress-l5 "
This line just hang forever for me

![image](https://github.com/datawire/emojivoto/assets/16439060/54668d89-efa2-4f5a-baea-baca4ab93164)

2023-05-30 16:56 UTC, knlambert commented on emojivoto-web-app/js/setup_dev_env.ps1
> +    telepresence intercept "$interceptName" --docker --context default -n "$Global:EMOJIVOTO_NS" --service web-app --port 8083:80 --ingress-port 80 --ingress-host "$svcName.ambassador" --ingress-l5 "
Do you have the issue ? Or is it a me problem ?

2023-05-31 17:37 UTC, jacoblbeck approved these changes

2023-05-31 17:44 UTC, knlambert approved these changes

2023-05-31 17:45 UTC, merged